name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Uninstall current ESLint (to switch to older version)
      run: npm uninstall eslint

    - name: Install ESLint 8.x
      run: npm install eslint@8.45.0 --save-dev

    - name: Ensure ESLint plugins are installed
      run: npm install @typescript-eslint/eslint-plugin@latest --save-dev

    - name: Run ESLint
      run: npx eslint .

