name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        cd frontend
        npm install

    - name: Install specific ESLint version
      run: |
        cd frontend
        npm install eslint@8.45.0 --save-dev

    - name: Run ESLint
      run: npx eslint .

